version: '3'
services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=test
    ports:
      - "9870:9870"
      - "9000:9000"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    volumes:
      - namenode:/hadoop/dfs/name

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    environment:
      - CLUSTER_NAME=test
      - NAMENODE_HOST=namenode
    ports:
      - "9864:9864"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    volumes:
      - datanode:/hadoop/dfs/data
    depends_on:
      - namenode

  hive-metastore-postgresql:
    image: postgres:12
    container_name: hive-metastore-postgresql
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    volumes:
      - metastore_db:/var/lib/postgresql/data

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    environment:
      - HIVE_METASTORE_DB_TYPE=postgres
      - HIVE_METASTORE_DB_HOST=hive-metastore-postgresql
      - HIVE_METASTORE_DB_NAME=metastore
      - HIVE_METASTORE_DB_USER=hive
      - HIVE_METASTORE_DB_PASS=hive
      - HIVE_METASTORE_URI=thrift://hive-metastore:9083
    ports:
      - "9083:9083"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    depends_on:
      - hive-metastore-postgresql
      - namenode

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    environment:
      - HIVE_METASTORE_URI=thrift://hive-metastore:9083
    ports:
      - "10000:10000"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    depends_on:
      - hive-metastore
      - datanode

volumes:
  namenode:
  datanode:
  metastore_db:
